/**
 * Export centralisé des composants UI — imports propres dans les vues.
 */
export { default as AppButton } from './AppButton.vue'
export { default as AppLink } from './AppLink.vue'
export { default as AppCard } from './AppCard.vue'
export { default as AppTitle } from './AppTitle.vue'
export { default as AppHeading } from './AppHeading.vue'
export { default as AppParagraph } from './AppParagraph.vue'
export { default as AppInput } from './AppInput.vue'
export { default as AppSelect } from './AppSelect.vue'
export { default as StatCard } from './StatCard.vue'
export { default as AppPagination } from './AppPagination.vue'
export { default as LanguageSwitcher } from './LanguageSwitcher.vue'
export { default as ThemeToggle } from './ThemeToggle.vue'
export { default as CurrencySwitcher } from './CurrencySwitcher.vue'
export { default as UserMenu } from './UserMenu.vue'
export { default as InfiniteMarquee } from './InfiniteMarquee.vue'
export { default as AppBottomNav } from './AppBottomNav.vue'
export { default as AppDropzone } from './AppDropzone.vue'
export { default as AppUpload } from './AppUpload.vue'
export { default as AppImage } from './AppImage.vue'
export { default as ViewSwitcher } from './ViewSwitcher.vue'
export { default as ConfirmModal } from './ConfirmModal.vue'
export { default as AppModal } from './AppModal.vue'
